name: Oshekher

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://cdn.discordapp.com/attachments/816996822627123204/863021293879689216/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/Phantom1721/Reference/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Phantom1721/Reference/main/wallpaper.png -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/Phantom1721/Reference/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Phantom1721/Reference/main/loop.bat -OutFile loop.bat
    - name: Extracting Ngrok Files
      run: Expand-Archive ngrok.zip
    - name: Connect To Ngrok Account
      run: .\ngrok\ngrok.exe authtoken 1GvzmW4PDo92bw6KoGSzTuynHTPJRVpHL6_2YsmMEjhtKT4cYSqi7daW

    - name: Enabling RDP Access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.png D:\a\wallpaper.png
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Membuat Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect to your RDP CPU 2 Core - 7GB Ram - 256 SSD
      run: cmd /c start.bat
    - name: Made Successfully! You Can Close Tab Now.
      run: cmd /c loop.bat
